name: cashew_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  auto_route: ^11.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  hive_ce: ^2.19.3
  syncfusion_flutter_charts: ^32.2.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.4.0
  build_runner: ^2.11.0

flutter:
  uses-material-design: true
